steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west2-docker.pkg.dev/dusty-chat-agent/quickstart-docker-repo/quickstart-image:latest', '.']
images:
  - 'us-west2-docker.pkg.dev/dusty-chat-agent/quickstart-docker-repo/quickstart-image:latest'