name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '380.0.0'

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > ${{ github.workspace }}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-service-key.json

      - name: Set project ID
        run: |
          gcloud config set project dusty-chat-agent

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dusty-chat-agent \
            --image=gcr.io/dusty-agent/dusty-chat-agent-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars=FLAVOR=production,API_BASE_URL=https://dustyagent.chat/api,JWT_SECRET=${{ secrets.JWT_SECRET }},DATABASE_URL=${{ secrets.DATABASE_URL_PROD }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          
      - name: Delete the service account key file
        run: |
          rm -f ${{ github.workspace }}/gcloud-service-key.json
