name: Deploy Backend

on:
  push:
    branches:
      - main  # 운영 배포는 main 브랜치에서만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Google Cloud Run
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCLOUD_SERVICE_KEY }}
          gcloud config set project your-gcp-project
          gcloud run deploy dusty-agent-backend \
            --image=gcr.io/your-gcp-project/dusty-agent-backend \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --set-env-vars=FLAVOR=production,API_BASE_URL=https://dustyagent.chat/api,JWT_SECRET=${{ secrets.JWT_SECRET }},DATABASE_URL=${{ secrets.DATABASE_URL_PROD }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}