name: Deploy Backend

on:
  push:
    branches:
      - main  # 운영 배포는 main 브랜치에서만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      
      # Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      # Set project ID
      - name: Set project ID
        run: gcloud config set project dusty-chat-agent

      # Docker Hub 로그인
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Docker Build & Push to Docker Hub
      - name: Build and Push Docker Image
        run: |
          docker build -t dustyagent/fastapi-app:latest .
          docker push dustyagent/fastapi-app:latest

      # Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dusty-chat-agent \
            --image=docker.io/dustyagent/fastapi-app:latest \
            --platform=managed \
            --region=asia-northeast3 \
            --allow-unauthenticated \
            --set-env-vars=FLAVOR=production,API_BASE_URL=https://dustyagent.chat/api,JWT_SECRET=${{ secrets.JWT_SECRET }},DATABASE_URL=${{ secrets.DATABASE_URL_PROD }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --port=8000
